// src/renderer/src/App.tsx
import React, { useState } from 'react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import Sidebar from './components/Sidebar'
import Logs from './components/Logs'
import { ImperativePanelHandle, Panel, PanelGroup, PanelResizeHandle } from 'react-resizable-panels'

// Initialize Query Client
const queryClient = new QueryClient()

const MainLayout: React.FC = () => {
  // Local state
  const [projectId, setProjectId] = useState<string | undefined>()
  const [sidebar, setSidebar] = useState<ImperativePanelHandle | null>(null) // PaneAPI equivalent
  const [isSidebarOpen, setIsSidebarOpen] = useState<boolean>(true)

  return (
    <QueryClientProvider client={queryClient}>
      <div className="h-screen">
        <PanelGroup direction="horizontal" className="h-full" autoSaveId="@layouts/main">
          {/* Sidebar Panel */}
          <Panel
            ref={setSidebar}
            collapsible
            minSize={20}
            defaultSize={20}
            maxSize={40}
            onCollapse={() => setIsSidebarOpen(false)}
            onExpand={() => setIsSidebarOpen(true)}
            className="bg-background-lighter"
          >
            <Sidebar
              sidebar={sidebar}
              projectId={projectId}
              onChangeProjectId={(newProjectId: string) => setProjectId(newProjectId)}
            />
          </Panel>

          {/* Panel Resizer */}
          <PanelResizeHandle
            className="px-1 -mx-1 flex items-center justify-center z-10"
            onDoubleClick={() => {
              if (sidebar?.resize) sidebar.resize(20) // Resize to 20% width
            }}
          >
            <div className="w-px h-full bg-border-light"></div>
          </PanelResizeHandle>

          {/* Logs Panel */}
          <Panel className="flex flex-col">
            {projectId && (
              <Logs projectId={projectId} sidebar={sidebar} isSidebarOpen={isSidebarOpen} />
            )}
          </Panel>
        </PanelGroup>
      </div>
    </QueryClientProvider>
  )
}

export default MainLayout

// src/renderer/src/App.svelte
<script lang="ts">
  import { PaneGroup, Pane, PaneResizer, type PaneAPI } from 'paneforge'
  import { QueryClientProvider } from '@tanstack/svelte-query'
  import Sidebar from './components/Sidebar.svelte'
  import Logs from './components/Logs.svelte'
  import { queryClient } from './lib/tanstack-query'

  // Local state
  let projectId: string = $state()
  let sidebar: PaneAPI = $state()
  let isSidebarOpen = $state(true)
</script>

<QueryClientProvider client={queryClient}>
  <div class="h-screen">
    <PaneGroup direction="horizontal" class="h-full" autoSaveId="@layouts/main">
      <Pane
        bind:pane={sidebar}
        collapsible
        minSize={20}
        defaultSize={20}
        maxSize={40}
        onCollapse={() => {
          isSidebarOpen = false
        }}
        onExpand={() => {
          isSidebarOpen = true
        }}
        class="bg-background-lighter"
      >
        <Sidebar
          {sidebar}
          {projectId}
          onChangeProjectId={(newProjectId) => {
            projectId = newProjectId
          }}
        />
      </Pane>

      <PaneResizer
        class="px-1 -mx-1 flex items-center justify-center z-10"
        ondblclick={() => {
          sidebar.resize(20)
        }}
      >
        <div class="w-px h-full bg-border-light"></div>
      </PaneResizer>

      <Pane class="flex flex-col">
        {#if projectId}
          <Logs {projectId} {sidebar} {isSidebarOpen} />
        {/if}
      </Pane>
    </PaneGroup>
  </div>
</QueryClientProvider>
