// src/renderer/src/components/Log.svelte
<script lang="ts">
  import { format } from 'date-fns'
  import { isObjectLike } from '../utils/is-object-like'
  import ObjectTree from './ObjectTree.svelte'
  import type { Log } from '../types/log'
  import DocumentOnDocument from '../icons/DocumentOnDocument.svelte'

  import Checkmark from '../icons/Checkmark.svelte'
  import { fade } from 'svelte/transition'

  let { log }: { log: Log } = $props()

  // Context menu template
  // Handle the right-click event
  function handleContextMenu(event: MouseEvent): void {
    event.preventDefault() // Prevent the default browser context menu
    window.api.showContextMenu(log.id).catch((err: unknown) => {
      console.error('Failed to show context menu:', err)
    })
  }

  let parsedLog = $derived.by(() => {
    let newLog = log

    if (newLog.content.startsWith('{') || newLog.content.startsWith('[')) {
      newLog = {
        ...newLog,
        content: JSON.parse(newLog.content)
      }
    }

    return newLog
  })

  let isCopied: boolean = $state(false)

  $effect(() => {
    window.api.onMenuItemClicked(async (event: string, logId: string) => {
      if (event === 'copy-log' && logId === log.id) {
        try {
          await navigator.clipboard.writeText(JSON.stringify(log, null, 2))
        } catch {
          window.alert('Failed to copy to clipboard')
        }
      }
    })
  })
</script>

<div
  tabindex={-1}
  class="grid grid-cols-4 hover:bg-background-lightest border-b border-border-light px-4"
  role="menu"
  oncontextmenu={handleContextMenu}
>
  <div class="p-2">
    <p class="text-foreground-muted truncate">
      {parsedLog.createdAt
        ? format(new Date(parsedLog.createdAt), 'MMM dd yyyy HH:mm:ss:SSS')
        : 'No date'}
    </p>
  </div>

  <div class="p-2 flex items-start gap-3 overflow-x-auto">
    <button
      type="button"
      title="Copy log"
      class="group rounded-md translate-y-[3px]"
      disabled={isCopied}
      onclick={async () => {
        isCopied = true

        try {
          await navigator.clipboard.writeText(JSON.stringify(parsedLog.content, null, 2))
        } catch {
          window.alert('Failed to copy to clipboard')
        }

        setTimeout(() => {
          isCopied = false
        }, 2000)
      }}
    >
      {#if isCopied}
        <Checkmark class="fill-foreground/40 w-4 h-4" />
      {:else}
        <DocumentOnDocument
          class="fill-foreground-muted group-hover:fill-foreground transition w-4 h-4"
        />
      {/if}</button
    >

    {#if isObjectLike(parsedLog.content) || Array.isArray(parsedLog.content)}
      <div class="json-viewer font-mono">
        <ObjectTree depth={1} json={parsedLog.content} />
      </div>
    {:else}
      <p class="truncate">{String(parsedLog.content)}</p>
    {/if}
  </div>

  <div class="p-2 flex">
    <p class="text-foreground-muted truncate">{parsedLog.project?.name}</p>
  </div>

  <div class="p-2">
    <p class="text-foreground-muted truncate">tree.tsx:2031:12</p>
  </div>
</div>

// src/renderer/src/components/Log.tsx
import React, { useState, useMemo } from 'react'
import { format } from 'date-fns'
import { isObjectLike } from '../utils/is-object-like'
import ObjectTree from './ObjectTree'
import DocumentOnDocument from '../icons/DocumentOnDocument'
import Checkmark from '../icons/Checkmark'

type Log = {
  id: string
  createdAt?: string
  content: string | object
  project?: { name: string }
}

type LogProps = {
  log: Log
}

const LogItem: React.FC<LogProps> = ({ log }) => {
  const [isCopied, setIsCopied] = useState(false)

  // Derived state for parsed log
  const parsedLog = useMemo(() => {
    if (
      typeof log.content === 'string' &&
      (log.content.startsWith('{') || log.content.startsWith('['))
    ) {
      try {
        return {
          ...log,
          content: JSON.parse(log.content)
        }
      } catch {
        // Fallback in case parsing fails
        return log
      }
    }
    return log
  }, [log])

  // Context menu handler
  //const handleContextMenu = (event: React.MouseEvent<HTMLDivElement>) => {
  //  event.preventDefault()
  //  window.api
  //    .showContextMenu(log.id)
  //    .catch((err: unknown) => console.error('Failed to show context menu:', err))
  //}

  //useEffect(() => {
  //  const handleMenuItemClick = async (event: string, logId: string) => {
  //    if (event === 'copy-log' && logId === log.id) {
  //      try {
  //        await navigator.clipboard.writeText(JSON.stringify(log, null, 2))
  //      } catch {
  //        window.alert('Failed to copy to clipboard')
  //      }
  //    }
  //  }
  //
  //  window.api.onMenuItemClicked(handleMenuItemClick)
  //}, [log])

  const handleCopyLog = async () => {
    setIsCopied(true)
    try {
      await navigator.clipboard.writeText(JSON.stringify(parsedLog.content, null, 2))
    } catch {
      window.alert('Failed to copy to clipboard')
    }
    setTimeout(() => setIsCopied(false), 2000)
  }

  return (
    <div
      tabIndex={-1}
      className="grid grid-cols-4 hover:bg-background-lightest border-b border-border-light px-4"
      role="menu"
      //onContextMenu={handleContextMenu}
    >
      {/* Date */}
      <div className="p-2">
        <p className="text-foreground-muted truncate">
          {parsedLog.createdAt
            ? format(new Date(parsedLog.createdAt), 'MMM dd yyyy HH:mm:ss:SSS')
            : 'No date'}
        </p>
      </div>

      {/* Content */}
      <div className="p-2 flex items-start gap-3 overflow-x-auto">
        <button
          type="button"
          title="Copy log"
          className="group rounded-md translate-y-[3px]"
          disabled={isCopied}
          onClick={handleCopyLog}
        >
          {isCopied ? (
            <Checkmark className="fill-foreground/40 w-4 h-4" />
          ) : (
            <DocumentOnDocument className="fill-foreground-muted group-hover:fill-foreground transition w-4 h-4" />
          )}
        </button>

        {isObjectLike(parsedLog.content) || Array.isArray(parsedLog.content) ? (
          <div className="json-viewer font-mono">
            <ObjectTree depth={1} json={parsedLog.content} />
          </div>
        ) : (
          <p className="truncate">{String(parsedLog.content)}</p>
        )}
      </div>

      {/* Project Name */}
      <div className="p-2 flex">
        <p className="text-foreground-muted truncate">{parsedLog.project?.name}</p>
      </div>

      {/* Location */}
      <div className="p-2">
        <p className="text-foreground-muted truncate">tree.tsx:2031:12</p>
      </div>
    </div>
  )
}

export default LogItem
