// src/renderer/src/components/ObjectTree.svelte
<script lang="ts">
  import cn from '../utils/classnames'
  import Self from './ObjectTree.svelte'

  let { json, depth = Infinity, _cur = 0, _last = true, search = '' } = $props()

  let items = $state([])
  let isArray = $state(false)
  let brackets = $state(['', ''])
  let collapsed = $state(false)

  /**
   * @param {*} i
   * @returns {string}
   */
  function getType(i: unknown): string {
    if (i === null) return 'null'
    return typeof i
  }

  /**
   * @param {*} i
   * @returns {string}
   */
  function stringify(i: unknown): string {
    return JSON.stringify(i)
  }

  /**
   * @param {*} i
   * @returns {string}
   */
  function format(i: unknown): string {
    switch (getType(i)) {
      case 'function':
        return 'f () {...}'
      case 'symbol':
        return i.toString()
      default:
        return stringify(i)
    }
  }

  function clicked(): void {
    collapsed = !collapsed
  }

  /**
   * @param {Event} e
   */
  function pressed(e: unknown): void {
    if (e instanceof KeyboardEvent && ['Enter', ' '].includes(e.key)) clicked()
  }

  $effect(() => {
    items = getType(json) === 'object' ? Object.keys(json) : []
    isArray = Array.isArray(json)
    brackets = isArray ? ['[', ']'] : ['{', '}']
  })

  //$: {
  //}

  $effect(() => {
    collapsed = depth < _cur
  })
</script>

{#if !items.length}
  <span class="_jsonBkt empty" class:isArray>{brackets[0]}{brackets[1]}</span>{#if !_last}<span
      class="_jsonSep">,</span
    >{/if}
{:else if collapsed}
  <span
    class="_jsonBkt"
    class:isArray
    role="button"
    tabindex="0"
    onclick={clicked}
    onkeydown={pressed}>{brackets[0]}...{brackets[1]}</span
  >{#if !_last && collapsed}<span class="_jsonSep">,</span>{/if}
{:else}
  <span
    class="_jsonBkt"
    class:isArray
    role="button"
    tabindex="0"
    onclick={clicked}
    onkeydown={pressed}>{brackets[0]}</span
  >
  <ul class="_jsonList">
    {#each items as i, idx}
      <li>
        {#if !isArray}
          <span class={cn('_jsonKey', i === search && 'bg-yellow-500')}>{stringify(i)}</span><span
            class="_jsonSep">:</span
          >
        {/if}
        {#if getType(json[i]) === 'object'}
          <Self json={json[i]} {depth} _cur={_cur + 1} _last={idx === items.length - 1} />
        {:else}
          <span class="_jsonVal {getType(json[i])}">{format(json[i])}</span
          >{#if idx < items.length - 1}<span class="_jsonSep">,</span>{/if}
        {/if}
      </li>
    {/each}
  </ul>
  <span
    class="_jsonBkt"
    class:isArray
    role="button"
    tabindex="0"
    onclick={clicked}
    onkeydown={pressed}>{brackets[1]}</span
  >{#if !_last}<span class="_jsonSep">,</span>{/if}
{/if}

<style>
  :where(._jsonList) {
    list-style: none;
    margin: 0;
    padding: 0;
    padding-left: var(--jsonPaddingLeft);
    border-left: var(--jsonBorderLeft);
  }
  :where(._jsonBkt) {
    color: hsl(var(--jsonBracketColor));
    border-radius: 4px;
    padding-block: 4px;
    padding-inline: 2px;
    margin-inline: -2px;
    margin-block: -4px;
  }
  :where(._jsonBkt):not(.empty):hover {
    background: hsl(var(--jsonBracketHoverBackground));
  }
  :where(._jsonSep) {
    color: hsl(var(--jsonSeparatorColor));
  }
  :where(._jsonKey) {
    color: hsl(var(--jsonKeyColor));
  }
  :where(._jsonVal) {
    color: hsl(var(--jsonValColor));
  }
  :where(._jsonVal).string {
    color: hsl(var(--jsonValStringColor));
  }
  :where(._jsonVal).number {
    color: hsl(var(--jsonValNumberColor));
  }
  :where(._jsonVal).boolean {
    color: hsl(var(--jsonValBooleanColor));
  }
</style>

// src/renderer/src/components/ObjectTree.tsx
import React, { useState, useEffect } from 'react'
import classNames from '../utils/classnames'
import ObjectTree from './ObjectTree'

type JsonTreeProps = {
  json: any
  depth?: number
  _cur?: number
  _last?: boolean
  search?: string
}

const JsonTree: React.FC<JsonTreeProps> = ({
  json,
  depth = Infinity,
  _cur = 0,
  _last = true,
  search = ''
}) => {
  const [items, setItems] = useState<string[]>([])
  const [isArray, setIsArray] = useState(false)
  const [brackets, setBrackets] = useState(['', ''])
  const [collapsed, setCollapsed] = useState(false)

  // Utility functions
  const getType = (value: unknown): string => {
    if (value === null) return 'null'
    return typeof value
  }

  const stringify = (value: unknown): string => {
    return JSON.stringify(value)
  }

  const format = (value: unknown): string => {
    switch (getType(value)) {
      case 'function':
        return 'f () {...}'
      case 'symbol':
        return value.toString()
      default:
        return stringify(value)
    }
  }

  const handleToggleCollapse = (): void => {
    setCollapsed((prev) => !prev)
  }

  const handleKeyPress = (e: React.KeyboardEvent): void => {
    if (['Enter', ' '].includes(e.key)) {
      handleToggleCollapse()
    }
  }

  // Effects
  useEffect(() => {
    setItems(getType(json) === 'object' ? Object.keys(json) : [])
    const isArrayCheck = Array.isArray(json)
    setIsArray(isArrayCheck)
    setBrackets(isArrayCheck ? ['[', ']'] : ['{', '}'])
  }, [json])

  useEffect(() => {
    setCollapsed(depth < _cur)
  }, [depth, _cur])

  // Render
  if (!items.length) {
    return (
      <span className={`_jsonBkt ${isArray ? 'isArray' : ''}`}>
        {brackets[0]}
        {brackets[1]}
        {!_last && <span className="_jsonSep">,</span>}
      </span>
    )
  }

  if (collapsed) {
    return (
      <>
        <span
          className={`_jsonBkt ${isArray ? 'isArray' : ''}`}
          role="button"
          tabIndex={0}
          onClick={handleToggleCollapse}
          onKeyDown={handleKeyPress}
        >
          {brackets[0]}...{brackets[1]}
        </span>
        {!_last && <span className="_jsonSep">,</span>}
      </>
    )
  }

  return (
    <>
      <span
        className={`_jsonBkt ${isArray ? 'isArray' : ''}`}
        role="button"
        tabIndex={0}
        onClick={handleToggleCollapse}
        onKeyDown={handleKeyPress}
      >
        {brackets[0]}
      </span>
      <ul className="_jsonList">
        {items.map((item, idx) => (
          <li key={idx}>
            {!isArray && (
              <>
                <span className={classNames('_jsonKey', item === search && 'bg-yellow-500')}>
                  {stringify(item)}
                </span>
                <span className="_jsonSep">:</span>
              </>
            )}
            {getType(json[item]) === 'object' ? (
              <ObjectTree
                json={json[item]}
                depth={depth}
                _cur={_cur + 1}
                _last={idx === items.length - 1}
              />
            ) : (
              <>
                <span className={`_jsonVal ${getType(json[item])}`}>{format(json[item])}</span>
                {idx < items.length - 1 && <span className="_jsonSep">,</span>}
              </>
            )}
          </li>
        ))}
      </ul>
      <span
        className={`_jsonBkt ${isArray ? 'isArray' : ''}`}
        role="button"
        tabIndex={0}
        onClick={handleToggleCollapse}
        onKeyDown={handleKeyPress}
      >
        {brackets[1]}
      </span>
      {!_last && <span className="_jsonSep">,</span>}
    </>
  )
}

export default JsonTree
