// src/renderer/src/components/Sidebar.svelte
<script lang="ts">
  import type { PaneAPI } from 'paneforge'
  import SidebarLeft from '../icons/SidebarLeft.svelte'
  import { fade } from 'svelte/transition'
  import cn from '../utils/classnames'
  import ShippingBoxFill from '../icons/ShippingBoxFill.svelte'
  import { createQuery } from '@tanstack/svelte-query'

  // Props
  let {
    sidebar,
    projectId,
    onChangeProjectId
  }: { sidebar: PaneAPI; projectId?: string; onChangeProjectId: (newProjectId: string) => void } =
    $props()

  // Server state
  const query = createQuery({
    queryKey: ['projects'],
    queryFn: () => window.api.getProjects()
  })

  let search = $state('')

  //let filteredProjects = $derived(
  //  FAKE_PROJECTS.filter((project) => project.name.toLowerCase().includes(search.toLowerCase()))
  //)
</script>

<div class="pl-[82px] items-center h-[52px] flex item-center gap-3 drag">
  <button
    type="button"
    title="Toggle sidebar"
    class="no-drag group rounded-md hover:bg-foreground/5 transition duration-700 px-[9px] py-2"
    onclick={(): void => {
      sidebar.collapse()
    }}
  >
    <SidebarLeft class="fill-foreground/40 group-active:fill-foreground transition w-6" />
  </button>
</div>

<div class="space-y-4">
  <div class="px-3">
    <button
      type="button"
      id="new-project"
      class="transition duration-150 border border-border-lighter w-full rounded-md py-1 pl-8 pr-2 bg-background-lightest hover:bg-background-lightest-hover hover:border-border-lighter-hover focus:outline-none focus:ring-2 ring-primary/25 shadow shadow-background"
      onclick={() => {
        const projectName = window.prompt('Project name')

        if (projectName) {
          window.api.createProject('New project')
        }
      }}>New project</button
    >
  </div>

  <div class="px-3 space-y-1.5 w-full">
    <p class="text-foreground-muted text-sm font-medium mx-2">Projects</p>

    {#if $query.isLoading}
      <p>Loading...</p>
    {:else if $query.isError}
      <p>Error: {$query.error.message}</p>
    {:else if $query.isSuccess}
      <div class="-space-y-0.5">
        {#each $query.data as project}
          <button
            transition:fade={{ duration: 50 }}
            onclick={() => {
              onChangeProjectId(project.id)
            }}
            class={cn(
              'flex items-center gap-2.5 text-left py-1.5 px-3 w-full rounded-md',
              project.id === projectId ? 'bg-background-lightest' : 'hover:bg-background-lightest'
            )}
          >
            <ShippingBoxFill class="w-4 fill-primary" />

            <p class="truncate flex-1">{project.name}</p>
          </button>
        {/each}
      </div>
    {/if}
  </div>
</div>

// src/renderer/src/components/Sidebar.tsx
import { MutableRefObject, useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import SidebarLeftIcon from '../icons/SidebarLeft'
import ShippingBoxFillIcon from '../icons/ShippingBoxFill'
import classNames from '../utils/classnames'
import { ImperativePanelHandle } from 'react-resizable-panels'
import { Link } from 'react-router'

type SidebarProps = {
  sidebar: MutableRefObject<ImperativePanelHandle | null> // PaneAPI equivalent
}

const Sidebar = ({ sidebar }: SidebarProps) => {
  const [search] = useState('')

  // Fetch projects
  const {
    data: projects = [],
    isLoading,
    isError,
    error
  } = useQuery({
    queryKey: ['projects'],
    queryFn: () => window.api.getProjects()
  })

  // Filtered projects based on search input
  const filteredProjects = projects.filter((project: { name: string }) =>
    project.name.toLowerCase().includes(search.toLowerCase())
  )

  return (
    <div id="sidebar">
      {/* Header Section */}
      <div className="pl-[82px] items-center h-[52px] flex item-center gap-3 drag">
        <button
          type="button"
          title="Toggle sidebar"
          className="no-drag group rounded-md hover:bg-foreground/5 transition duration-700 px-[9px] py-2"
          onClick={() => {
            sidebar.current?.collapse()
          }}
        >
          <SidebarLeftIcon className="fill-foreground/40 group-active:fill-foreground transition w-6" />
        </button>
      </div>

      <div className="space-y-4">
        {/* New Project Button */}
        <div className="px-3">
          <button
            type="button"
            id="new-project"
            className="transition duration-150 border border-border-lighter w-full rounded-md py-1 pl-8 pr-2 bg-background-lightest hover:bg-background-lightest-hover hover:border-border-lighter-hover focus:outline-none focus:ring-2 ring-primary/25 shadow shadow-background"
            onClick={() => {
              const projectName = window.prompt('Project name')

              if (projectName) {
                window.api.createProject(projectName)
              }
            }}
          >
            New project
          </button>
        </div>

        {/* Projects List */}
        <div className="px-3 space-y-1.5 w-full">
          <p className="text-foreground-muted text-sm font-medium mx-2">Projects</p>

          {isLoading && <p>Loading...</p>}
          {isError && <p>Error: {error?.message || 'Unknown error'}</p>}
          {projects.length > 0 && (
            <div className="-space-y-0.5">
              {filteredProjects.map((project: { id: string; name: string }) => (
                <Link
                  to={`/${project.id}`}
                  key={project.id}
                  //onClick={() => onChangeProjectId(project.id)}
                  className={classNames(
                    'flex items-center gap-2.5 text-left py-1.5 px-3 w-full rounded-md',
                    project.id === 'TODO: Use variable here'
                      ? 'bg-background-lightest'
                      : 'hover:bg-background-lightest'
                  )}
                >
                  <ShippingBoxFillIcon className="w-4 fill-primary" />
                  <p className="truncate flex-1">{project.name}</p>
                </Link>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

export default Sidebar
